Lesson16
gloomy-onion/pizza2 pull request #2
Opened 2023-11-21 11:27 UTC by gloomy-onion

2023-11-21 15:49 UTC, Alterqq requested changes

2023-11-21 15:49 UTC, Alterqq commented on src/Cart/Cart.jsx
> +    if (window.confirm('Очистить корзину?'))
if (window.confirm('Очистить корзину?')) {
  dispatch(clearItems);
 }

2023-11-21 15:49 UTC, Alterqq commented on src/Cart/Cart.jsx
> +              <div className={styles.cart__clear} onClick={onClickClear}>
button, а не div

2023-11-21 15:49 UTC, Alterqq commented on src/Cart/CartItem.jsx
> +      dispatch(removeItem(id));
скобочки

2023-11-21 15:49 UTC, Alterqq commented on src/Cart/CartItem.jsx
> +          disabled={count === 1}
самозакрывающийся тег (?)

2023-11-21 15:49 UTC, Alterqq commented on src/Cart/Cart.jsx
> +  const totalCount = items.reduce((sum, item) => sum + item.count, 0);
Дублирование логики в Header, есть смысл вынести в редакс

2023-11-21 15:49 UTC, Alterqq commented on src/redux/Slices/cartSlice.js
> +        }, 0);
Перенести сюда логику totalCount

2023-11-21 15:49 UTC, Alterqq commented on src/redux/Slices/cartSlice.js
> +        if (findItem) {
if (findItem && findItem.count > 1)

2023-11-21 15:49 UTC, Alterqq commented on src/redux/Slices/pizzaSlice.js
> +export const fetchPizzas = createAsyncThunk('pizza/fetchPizzasStatus', async ({params}) => {
(params) =>

2023-11-21 15:49 UTC, Alterqq commented on src/redux/Slices/pizzaSlice.js
> +        state.status = 'loading';
state.status = 'success' или другой статус, говорящий об успехе

2023-11-22 12:30 UTC, gloomy-onion commented on src/Cart/CartItem.jsx
> +          disabled={count === 1}
я так поняла что если не компонент то нет

2023-11-24 11:33 UTC, Alterqq commented on src/MainContent/MainContent.jsx
> +      console.log(isSearch.current);
лишний консоль лог

2023-11-24 11:37 UTC, merged